version: '3'
services:
  app:
    image: ghcr.io/consenti-ai/blocksee-sales-agent@sha256:2842fe0d45e156e9fb10f89200efb03f9b275349a381a2a76d7a6617cbb80054
    env_file:
      - .env.secretvm
    networks:
      - appnet
  traefik:
    image: traefik:v2.10
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.options=default@file
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/secure/cert:/certs:ro
    networks:
      - appnet
    configs:
      - source: dynamic_config
        target: /etc/traefik/dynamic/dynamic.yml
networks:
  appnet:
    driver: bridge
configs:
  dynamic_config:
    content: |-
      tls:
        options:
          default:
            minVersion: VersionTLS12
        stores:
          default:
            defaultCertificate:
              certFile: /certs/secret_vm_fullchain.pem
              keyFile: /certs/secret_vm_private.pem
        certificates:
          - certFile: /certs/secret_vm_fullchain.pem
            keyFile: /certs/secret_vm_private.pem
      http:
        routers:
          app:
            rule: "PathPrefix(`/`)"
            entryPoints:
              - websecure
            service: app
            tls: {}
        services:
          app:
            loadBalancer:
              servers:
                - url: "http://app:3000"
