http:
  routers:
    app:
      rule: "Host(`teal-toad.vm.scrtlabs.com`)"
      entryPoints:
        - websecure
      service: app
      tls: {}
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:3000"

tls:
  certificates:
    - certFile: /certs/secret_vm_fullchain.pem
      keyFile: /certs/secret_vm_private.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/secret_vm_fullchain.pem
        keyFile: /certs/secret_vm_private.pem
